# Generated by Django 2.2 on 2019-04-22 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resposta',
            name='corretude',
            field=models.BooleanField(default=False),
        ),
    ]
