# Generated by Django 2.2 on 2019-04-22 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_auto_20190422_1053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pergunta',
            name='pergunta',
            field=models.TextField(),
        ),
    ]
