# Generated by Django 2.0.13 on 2019-04-23 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_auto_20190422_1054'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='create_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
