# Generated by Django 2.2 on 2019-04-23 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0004_quiz_create_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resposta',
            name='resposta',
            field=models.CharField(max_length=200),
        ),
    ]
