# Generated by Django 2.2 on 2019-04-23 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0005_auto_20190423_1401'),
    ]

    operations = [
        migrations.AddField(
            model_name='pergunta',
            name='resposta',
            field=models.CharField(default='', max_length=1000),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Resposta',
        ),
    ]
