# Generated by Django 2.2 on 2019-04-29 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0007_auto_20190423_1550'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='numPerguntas',
            field=models.IntegerField(default=1),
        ),
    ]
