# Generated by Django 2.2 on 2019-04-29 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0008_auto_20190428_2133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='numPerguntas',
            field=models.IntegerField(),
        ),
    ]
