# Generated by Django 2.0.13 on 2019-04-21 19:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Aventura',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('aventura', models.TextField(default='')),
                ('genero', models.CharField(choices=[('TR', 'Terror'), ('MD', 'Medieval'), ('CY', 'Cyberpunk'), ('MO', 'Moderno')], default='TR', max_length=2)),
                ('itens', models.TextField()),
                ('numeroDeJogadores', models.IntegerField(default=2)),
                ('npcs', models.TextField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('classe', models.CharField(max_length=25)),
                ('tamanho', models.IntegerField(blank=True, default=0, null=True)),
                ('raca', models.CharField(choices=[('HUM', 'HUMANO'), ('DRA', 'DRACONATOS'), ('ELF', 'ELFOS'), ('GNO', 'GNOMOS'), ('ANO', 'ANOES'), ('HAL', 'HALFLINGS'), ('ELA', 'ELADRIN')], default='HUMANO', max_length=15)),
                ('idade', models.IntegerField(default=0)),
                ('sexo', models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino')], max_length=1)),
                ('altura', models.FloatField(default=0)),
                ('peso', models.FloatField(default=0)),
                ('olhos', models.CharField(max_length=20)),
                ('cabelo', models.CharField(max_length=30)),
                ('pele', models.CharField(max_length=30)),
                ('divindade', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('tendencia', models.CharField(choices=[('LG', 'LAWFUL GOOD'), ('NG', 'NEUTRAL GOOD'), ('CG', 'CHAOTIC GOOD'), ('LN', 'LAWFUL NEUTRAL'), ('TN', 'TRUE NEUTRAL'), ('CN', 'CHAOTIC NEUTRAL'), ('LE', 'LAWFUL EVIL'), ('NE', 'NEUTRAL EVIL'), ('CE', 'CHAOTIC EVIL')], default='LG', max_length=2)),
                ('idiomas', models.TextField(blank=True, default='', null=True)),
                ('forca', models.IntegerField(default=0)),
                ('constituicao', models.IntegerField(default=0)),
                ('destreza', models.IntegerField(default=0)),
                ('inteligencia', models.IntegerField(default=0)),
                ('sabedoria', models.IntegerField(default=0)),
                ('carisma', models.IntegerField(default=0)),
                ('pontosDeVida', models.IntegerField(default=5)),
                ('iniciativa', models.IntegerField(default=0)),
                ('deslocamento', models.IntegerField(default=2)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Pericias',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('character', models.IntegerField()),
                ('acrobacia', models.IntegerField(default=0)),
                ('atletismo', models.IntegerField(default=0)),
                ('blefe', models.IntegerField(default=0)),
                ('diplomacia', models.IntegerField(default=0)),
                ('exploracao', models.IntegerField(default=0)),
                ('furtividade', models.IntegerField(default=0)),
                ('historia', models.IntegerField(default=0)),
                ('intimidacao', models.IntegerField(default=0)),
                ('intuicao', models.IntegerField(default=0)),
                ('ladinagem', models.IntegerField(default=0)),
                ('manha', models.IntegerField(default=0)),
                ('natureza', models.IntegerField(default=0)),
                ('percepcao', models.IntegerField(default=0)),
                ('religiao', models.IntegerField(default=0)),
                ('socorro', models.IntegerField(default=0)),
                ('tolerancia', models.IntegerField(default=0)),
                ('rosto', models.ImageField(upload_to='media')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('text', models.TextField()),
                ('create_date', models.DateTimeField(blank=True, null=True)),
                ('categoria', models.CharField(choices=[('AV', 'Aventura'), ('PR', 'Personagem'), ('IT', 'Item'), ('FC', 'Ficha'), ('TM', 'Tema Livre')], default='AV', max_length=2)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RespostaPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resposta', models.TextField()),
                ('respResp', models.BooleanField(default=False)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Post')),
                ('repostaMain', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.RespostaPost')),
            ],
        ),
        migrations.CreateModel(
            name='Teste',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
            ],
        ),
    ]
