# Generated by Django 2.0.13 on 2019-04-21 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pericias',
            name='rosto',
        ),
        migrations.AddField(
            model_name='character',
            name='rosto',
            field=models.ImageField(default='', upload_to='media'),
            preserve_default=False,
        ),
    ]
