# Generated by Django 2.0.13 on 2019-04-21 20:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20190421_1701'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='character',
            name='rosto',
        ),
    ]
