# Generated by Django 2.0.13 on 2019-04-21 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_character_rosto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='rosto',
            field=models.ImageField(default='', upload_to='images'),
            preserve_default=False,
        ),
    ]
