# Generated by Django 2.0.13 on 2019-04-21 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20190421_1749'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='rosto',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
    ]
