# Generated by Django 2.0.13 on 2019-04-21 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20190421_1806'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, default='', upload_to='images'),
            preserve_default=False,
        ),
    ]
