# Generated by Django 2.0.13 on 2019-04-21 21:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_auto_20190421_1810'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='character',
            name='rosto',
        ),
        migrations.RemoveField(
            model_name='post',
            name='image',
        ),
    ]
