# Generated by Django 2.2 on 2019-04-25 02:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_auto_20190421_1815'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Teste',
        ),
    ]
