# Generated by Django 2.2 on 2019-04-27 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_delete_teste'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aventura',
            old_name='numeroDeJogadores',
            new_name='numeroJogadores',
        ),
    ]
