# Generated by Django 2.2 on 2019-04-29 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_auto_20190427_1115'),
    ]

    operations = [
        migrations.AddField(
            model_name='aventura',
            name='create_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
